### ISSUE TITLE
Problem with producer using zookeeper

### ISSUE THREAD

**Issue by dhirajpraj** [dannycoates/franz-kafka#12]
It is not taking the correct kafka host and port. It gives the following error:

zk get testKafkatopic1 children
connecting broker 2 host -1,"timestamp" port "1426664058286","host"
net.js:901
      throw new RangeError('port should be > 0 and < 65536: ' + port);
            ^
RangeError: port should be > 0 and < 65536: 0
    at Socket.connect (net.js:901:13)
    at Object.exports.connect.exports.createConnection (net.js:92:35)

**Comment by dannycoates** [comment]
I'm not actively maintaining this code anymore, sorry.
