### ISSUE TITLE
NPM Still at Version 0.7.4 and readable-stream repo has been deleted.

### ISSUE THREAD

**Issue by No9** [dannycoates/franz-kafka#5]
I see that this https://github.com/dannycoates/franz-kafka/pull/4 landed but npm is not updated as it is still showing 0.7.4 when the current package.json has 0.7.5
This is causing npm install franz-kafka to fail. 

Any idea when npm will be updated? 

Thanks

**Comment by dannycoates** [comment]
pushed. sorry for the delay
